package com.jio.crm.dms.countermanager;

import java.util.concurrent.atomic.LongAdder;

/**
 * 
 * This Class Define Counter Name
 * 
 * @author Ashish14.Gupta
 *
 */

public enum CounterNameEnum {

	// ES Index Counter

	CNTR_ES_INDEX_CREATION_REQUESTS,

	CNTR_ES_INDEX_CREATION_SUCCESS,

	CNTR_ES_INDEX_CREATION_FAILURE,

	// ES Document Create Counter

	CNTR_ES_DOCUMENTS_CREATED_TOTAL,

	CNTR_ES_DOCUMENTS_CREATION_SUCCESS,

	CNTR_ES_DOCUMENTS_CREATION_FAILURE,

	// ES Search Request Counter

	CNTR_ES_SEARCH_REQUESTS,

	CNTR_ES_SEARCH_SUCCESS,

	CNTR_ES_SEARCH_FAILURE,

	// common failure

	CNTR_COMMON_FAILURE,

	// Counter for File upload,download,validate and get columns data
	CNTR_GET_FILE_REQUEST,

	CNTR_GET_FILE_SUCCESS,

	CNTR_GET_FILE_FAILURE,

	CNTR_DELETE_FILE_REQUEST,

	CNTR_DELETE_FILE_SUCCESS,

	CNTR_DELETE_FILE_FAILURE,

	CNTR_DOWNLOAD_FILE_IN_BULK_REQUEST,

	CNTR_DOWNLOAD_FILE_IN_BULK_SUCCESS,

	CNTR_DOWNLOAD_FILE_IN_BULK_FAILURE,

	CNTR_SEARCH_FILE_DOCUMENT_REQUEST,

	CNTR_SEARCH_FILE_DOCUMENT_SUCCESS,

	CNTR_SEARCH_FILE_DOCUMENT_FAILURE,

	CNTR_DOWNLOAD_FILE_IN_BULK_EXCEL_REQUEST,

	CNTR_DOWNLOAD_FILE_IN_BULK_EXCEL_SUCCESS,

	CNTR_DOWNLOAD_FILE_IN_BULK_EXCEL_FAILURE,

	CNTR_MOVE_FILE_FROM_TEMP_TO_ORDER_REQUEST,

	CNTR_MOVE_FILE_FROM_TEMP_TO_ORDER_SUCCESS,

	CNTR_MOVE_FILE_FROM_TEMP_TO_ORDER_FAILURE,

	CNTR_FETCH_DOCUMENT_CATEGORY_REQUEST,

	CNTR_FETCH_DOCUMENT_CATEGORY_SUCCESS,

	CNTR_FETCH_DOCUMENT_CATEGORY_FAILURE,

	CNTR_UPLOAD_FILE_REQUEST,

	CNTR_UPLOAD_FILE_SUCCESS,

	CNTR_UPLOAD_FILE_FAILURE,

	CNTR_UPLOAD_UOL_FILE_REQUEST,

	CNTR_UPLOAD_UOL_FILE_SUCCESS,

	CNTR_UPLOAD_UOL_FILE_FAILURE,

	CNTR_VALIDATE_COLUMN_REQUEST,

	CNTR_VALIDATE_COLUMN_SUCCESS,

	CNTR_VALIDATE_COLUMN_FAILURE,

	CNTR_GET_COLUMN_VALUES_REQUEST,

	CNTR_GET_COLUMN_VALUES_SUCCESS,

	CNTR_GET_COLUMN_VALUES_FAILURE,

	// Rest Call Request Counter

	CNTR_SEND_REST_REQUEST,

	CNTR_SEND_REST_ACCEPTED,

	CNTR_SEND_REST_SUCCESS,

	CNTR_SEND_REST_FAILURE,

	GET_FETCH_LOCATION_LIST_SUCCESS,

	GET_FETCH_LOCATION_LIST_FAILURE,

	CNTR_CHANGE_FILE_DOCUMENT_TO_DEACTIVATED_FOLDER_REQUEST,

	CNTR_CHANGE_FILE_DOCUMENT_TO_DEACTIVATED_FOLDER_SUCCESS,

	CNTR_CHANGE_FILE_DOCUMENT_TO_DEACTIVATED_FOLDER_FAILURE,

	CNTR_UPLOAD_FILE_BY_DOCUMENT_CATEGORY_REQUEST,
	CNTR_UPLOAD_FILE_BY_DOCUMENT_CATEGORY_FAILURE,
	CNTR_UPLOAD_FILE_BY_DOCUMENT_CATEGORY_SUCCESS,
	CNTR_GET_FILE_BY_DOCUMENT_TYPE_REQUEST,
	CNTR_GET_FILE_BY_DOCUMENT_TYPE_SUCCESS,
	CNTR_GET_FILE_BY_DOCUMENT_TYPE_FAILURE,
	CNTR_FILE_UPLOAD_REQUEST,
	CNTR_FILE_UPLOAD_FAILURE,
	CNTR_FILE_UPLOAD_SUCCESS,
	CNTR_GET_FILE_BY_URL_REQUEST,
	CNTR_GET_FILE_BY_URL_SUCCESS,
	CNTR_GET_FILE_BY_URL_FAILURE,
	CNTR_MOVE_FILE_FROM_TEMP_TO_LOCATION_ID_REQUEST,
	CNTR_MOVE_FILE_FROM_TEMP_TO_FAILURE,
	CNTR_MOVE_FILE_FROM_TEMP_TO_LOCATION_ID_FAILURE,
	CNTR_MOVE_FILE_FROM_TEMP_TO_LOCATION_ID_SUCCESS,
	CNTR_ARCHIVAL_FILES_REQUEST,
	CNTR_RESPONSE_CHECK_REQUEST,
	CNTR_ADD_CUSTOMERID_IN_DOCUMENT_REQUEST,
	CNTR_RELOAD_DOCUMENT_CATEGORY_REQUEST,
	CNTR_GET_TEMPLATE_FOR_FILES_SEARCH_REQUEST,
	CNTR_GET_TEMPLATE_FOR_FILES_SEARCH_SUCCESS,
	CNTR_GET_TEMPLATE_FOR_FILES_SEARCH_FAILURE,
	CNTR_ARCHIVAL_FILES_VIA_FTP_SUCCESS,
	CNTR_ARCHIVAL_FILES_VIA_FTP_FAILURE,
	CNTR_RESPONSE_CHECK_SUCCESS,
	CNTR_UPLOAD_MINIO_FILE_FAILURE,
	CNTR_UPLOAD_MINIO_FILE_SUCCESS;

	private LongAdder counter;

	private CounterNameEnum() {
		this.counter = new LongAdder();
	}

	/**
	 * reset the counter value to 0
	 */
	public void reset() {
		this.counter.reset();
	}

	/**
	 * increment the counter value by 1
	 */
	public void increment() {
		this.counter.increment();
	}

	/**
	 * @return the current value of the counter
	 */
	public long getValue() {
		return counter.longValue();
	}

}